// Compile with:
// glslc color_line_kernel.comp -o color_line_kernel.spv

#version 460

layout (local_size_x = 64, local_size_y = 1, local_size_z = 1) in;
layout (set = 1, binding = 0, rgba8) uniform writeonly image2D outImage;
layout (set = 2, binding = 0) uniform UBO {
    float r;
    float g;
    float b;
} ubo;

void main() {
    uint id = gl_GlobalInvocationID.x;
    imageStore(outImage, ivec2(id, id), vec4(ubo.r, ubo.g, ubo.b, 1.0));
}
